name: maac
repository: https://github.com/MinhMark123123/maac

sdkPath: /Users/minhnguyen/development/flutter

packages:
 - packages/**
 - examples/
 - doc/**

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    exec: dart analyze .
  description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  markdown-check:
    run: markdownlint . --ignore-path .markdownlintignore --config .markdownlint.yaml
    description: Runs the markdown linting check.

  markdown-fix:
    run: markdownlint . --fix --ignore-path .markdownlintignore --config .markdownlint.yaml
    description: Fixes the markdown linting errors.

  dartdoc:
    run: melos exec flutter pub run dartdoc
    description: Run dartdoc checks for all packages.

  test:select:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.