name: maac_mvvm_with_riverpod
description: maac_mvvm_with_riverpod is an extension package of maac_mvvm that is used with RiverPod.
version: 0.1.0
homepage: https://github.com/MinhMark123123/maac

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.5+1
  maac_mvvm: ^0.1.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
