name: maac_mvvm_with_riverpod
description: maac_mvvm_with_riverpod is an extension package of maac_mvvm that is used with RiverPod.
version: 0.2.0
homepage: https://github.com/MinhMark123123/maac
repository: https://github.com/MinhMark123123/maac
issue_tracker: https://github.com/MinhMark123123/maac/issues

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  maac_mvvm: ^0.2.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner:


flutter:
