name: maac_mvvm_generator_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  maac_mvvm: ^0.2.3
  maac_mvvm_annotation: ^0.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mockito: ^5.6.4
  maac_mvvm_generator: ^0.0.4+1

flutter:
  uses-material-design: true