import 'package:example/theme/color/app_colors.dart';
import 'package:flutter/material.dart';

final Color _lightFocusColor = Colors.black.withOpacity(0.12);

class LightColors extends AppColors {
  LightColors()
      : super(
          focusColor: _lightFocusColor,
          colorScheme: const ColorScheme(
            primary: Color(0xFFB93C5D),
            primaryContainer: Color(0xFF117378),
            secondary: Color(0xFFEFF3F3),
            secondaryContainer: Color(0xFFFAFBFB),
            background: Color(0xFFE6EBEB),
            surface: Color(0xFFFAFBFB),
            onBackground: Colors.white,
            error: Colors.black,
            onError: Colors.black,
            onPrimary: Colors.black,
            onSecondary: Color(0xFF322942),
            onSurface: Color(0xFF241E30),
            brightness: Brightness.light,
          ),
          extension: LightColorExtension(
            accent: const Color(0xffF86110),
            primary: const Color(0xff8C95A3),
            background: const Color(0xFF1B212C),
            container: const Color(0xff131821),
            bottomNav: const Color(0xff263240),
            primaryText: const Color(0xffFFFFFF),
            selectedText: const Color(0xFF1B212C),
            tabBGActivate: const Color(0xffB5BDC9),
            divider: const Color(0xff313C4E),
            badge: const Color(0xffFF0000),
            highlightSelected: const Color(0xffD9C678),
            increase: const Color(0xffED2355),
            decrease: const Color(0xff008CFE),
            tabBG: const Color(0xff2A3548),
            shadow: const Color(0x1F000000),
            border: const Color(0xff414A50),
            credit: const Color(0xff5D415E),
            disabled: const Color(0xFF2B3340),
            textDisabled: const Color.fromRGBO(255, 255, 255, 0.25),
            subText: const Color(0xffCECECE),
            secondaryText: const Color(0xff8C95A3),
            boxShadow: const Color(0x00000029),
            loadingBackground: const Color(0xff29303C),
            buttonCalculatorColor: const Color(0xff4D525C),
            itemCurrencySelected: const Color(0xffD9DCE2),
            actual: const Color(0xff245F24),
            future: const Color(0xffB26462),
            op: const Color(0xff335F7D),
            dialogSurface: const Color(0xff0B0E12),
            important: const Color(0xffE50017),
            trackColorSwitch: const Color(0xff4F5662),
            tradeBan: const Color(0xffF00B04),
            itemCurrency: const Color(0xff2A3548),
            decreaseOpacity10: const Color.fromRGBO(0, 140, 254, 0.1),
            increaseOpacity10: const Color.fromRGBO(237, 35, 85, 0.1),
            whiteOpacity10: const Color.fromRGBO(255, 255, 255, 0.1),
            stockIncrease: const Color(0xffCC0033),
            stockDecrease: const Color(0xff0070CC),
            flashed: const Color(0xffFFFF00),
          ),
        );
}

class LightColorExtension extends AppColorsExtension {
  LightColorExtension({
    required super.accent,
    required super.primary,
    required super.background,
    required super.bottomNav,
    required super.primaryText,
    required super.selectedText,
    required super.subText,
    required super.secondaryText,
    required super.container,
    required super.tabBGActivate,
    required super.tabBG,
    required super.divider,
    required super.badge,
    required super.highlightSelected,
    required super.decrease,
    required super.increase,
    required super.border,
    required super.shadow,
    required super.credit,
    required super.disabled,
    required super.textDisabled,
    required super.boxShadow,
    required super.loadingBackground,
    required super.buttonCalculatorColor,
    required super.itemCurrencySelected,
    required super.actual,
    required super.future,
    required super.op,
    required super.dialogSurface,
    required super.important,
    required super.trackColorSwitch,
    required super.tradeBan,
    required super.itemCurrency,
    required super.decreaseOpacity10,
    required super.increaseOpacity10,
    required super.whiteOpacity10,
    required super.stockIncrease,
    required super.stockDecrease,
    required super.flashed,
  });
}
