name: maac_mvvm_with_get_it
description: maac_mvvm_with_get_it is an extension package of maac_mvvm that is used with GetIt.
version: 0.2.2
homepage: https://github.com/MinhMark123123/maac
repository: https://github.com/MinhMark123123/maac
issue_tracker: https://github.com/MinhMark123123/maac/issues

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

resolution: workspace

dependencies:

  flutter:
    sdk: flutter
  get_it: ^9.2.1
  maac_mvvm: ^0.2.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.4
  build_runner:

flutter: