name: maac_mvvm
description: maac_mvvm is a package that supports simple implementation of the MVVM pattern. The package doesn't wrap any dependency 
  injection inside. With this, you can choose any framework dependency injection you want.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  async:
  visibility_detector:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter: