builders:
  mutable_state_generator|mutableStateGeneratorBuilder:
    import: "package:maac_mvvm_generator/maac_mvvm_generator.dart"
    builder_factories: ["bindingBuilder"]
    build_extensions: {".dart": [".binding.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]