name: maac_mvvm_with_get_it_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^8.0.2
  maac_mvvm_with_get_it:
    path: ../../maac_mvvm_with_get_it
  visibility_detector: ^0.4.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
